### ISSUE TITLE
Textract not installing on Python 3.6.4 on macOS High Sierra

### ISSUE THREAD

**Issue by parleychat** [deanmalmgren/textract#220]
I tried to install Textract on my Mac, and I keep having the same following problem (see below). I have made a lot of research online and I did not find anything helpful. 

This is what I have already done: 
- update swig
- Go to libsphinxad/ad_openal and change the header #include <al.h> to #include <OpenAL/al.h>
Nothing seems to work.

Thanks in advance for any help.
Below is the list of error: 

______________________________________________ ERROR MESSAGE ______________________________

Apples-MBP:~ Mac$ pip install textract
Collecting textract
Collecting pocketsphinx==0.1.3 (from textract)
  Using cached pocketsphinx-0.1.3.tar.bz2
Collecting xlrd==1.0.0 (from textract)
  Using cached xlrd-1.0.0-py3-none-any.whl
Requirement already satisfied: argcomplete==1.8.2 in /anaconda3/lib/python3.6/site-packages (from textract)
Requirement already satisfied: EbookLib==0.15 in /anaconda3/lib/python3.6/site-packages (from textract)
Requirement already satisfied: docx2txt==0.6 in /anaconda3/lib/python3.6/site-packages (from textract)
Requirement already satisfied: beautifulsoup4==4.5.3 in /anaconda3/lib/python3.6/site-packages (from textract)
Requirement already satisfied: python-pptx==0.6.5 in /anaconda3/lib/python3.6/site-packages (from textract)
Requirement already satisfied: chardet==2.3.0 in /anaconda3/lib/python3.6/site-packages (from textract)
Requirement already satisfied: six==1.10.0 in /anaconda3/lib/python3.6/site-packages (from textract)
Requirement already satisfied: SpeechRecognition==3.6.3 in /anaconda3/lib/python3.6/site-packages (from textract)
Requirement already satisfied: lxml in /anaconda3/lib/python3.6/site-packages (from EbookLib==0.15->textract)
Requirement already satisfied: Pillow>=2.6.1 in /anaconda3/lib/python3.6/site-packages (from python-pptx==0.6.5->textract)
Requirement already satisfied: XlsxWriter>=0.5.7 in /anaconda3/lib/python3.6/site-packages (from python-pptx==0.6.5->textract)
Building wheels for collected packages: pocketsphinx
  Running setup.py bdist_wheel for pocketsphinx ... error
  Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/rz/shzsvwdn5wb1dtt_kz8j5j3w0000gp/T/pip-build-ynl5coeg/pocketsphinx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/rz/shzsvwdn5wb1dtt_kz8j5j3w0000gp/T/tmpt5mxj21ppip-wheel- --python-tag cp36:
  running bdist_wheel
  running build_ext
  building 'sphinxbase._ad' extension
  swigging swig/sphinxbase/ad.i to swig/sphinxbase/ad_wrap.c
  swig -python -modern -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -I/System/Library/Frameworks/OpenAL.framework/Versions/A/Headers -Ideps/sphinxbase/include/android -Ideps/sphinxbase/swig -outdir sphinxbase -o swig/sphinxbase/ad_wrap.c swig/sphinxbase/ad.i
  creating build
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/swig
  creating build/temp.macosx-10.7-x86_64-3.6/swig/sphinxbase
  creating build/temp.macosx-10.7-x86_64-3.6/deps
  creating build/temp.macosx-10.7-x86_64-3.6/deps/sphinxbase
  creating build/temp.macosx-10.7-x86_64-3.6/deps/sphinxbase/src
  creating build/temp.macosx-10.7-x86_64-3.6/deps/sphinxbase/src/libsphinxad
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -I/System/Library/Frameworks/OpenAL.framework/Versions/A/Headers -Ideps/sphinxbase/include/android -I/anaconda3/include/python3.6m -c swig/sphinxbase/ad_wrap.c -o build/temp.macosx-10.7-x86_64-3.6/swig/sphinxbase/ad_wrap.o -Wno-macro-redefined -Wno-sign-compare -Wno-logical-op-parentheses
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -I/System/Library/Frameworks/OpenAL.framework/Versions/A/Headers -Ideps/sphinxbase/include/android -I/anaconda3/include/python3.6m -c deps/sphinxbase/src/libsphinxad/ad_openal.c -o build/temp.macosx-10.7-x86_64-3.6/deps/sphinxbase/src/libsphinxad/ad_openal.o -Wno-macro-redefined -Wno-sign-compare -Wno-logical-op-parentheses
  deps/sphinxbase/src/libsphinxad/ad_openal.c:43:10: fatal error: 'al.h' file not found
  #include <al.h>
           ^~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pocketsphinx
  Running setup.py clean for pocketsphinx
Failed to build pocketsphinx
Installing collected packages: pocketsphinx, xlrd, textract
  Running setup.py install for pocketsphinx ... error
    Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/rz/shzsvwdn5wb1dtt_kz8j5j3w0000gp/T/pip-build-ynl5coeg/pocketsphinx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/rz/shzsvwdn5wb1dtt_kz8j5j3w0000gp/T/pip-jefu9wtk-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building 'sphinxbase._ad' extension
    swigging swig/sphinxbase/ad.i to swig/sphinxbase/ad_wrap.c
    swig -python -modern -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -I/System/Library/Frameworks/OpenAL.framework/Versions/A/Headers -Ideps/sphinxbase/include/android -Ideps/sphinxbase/swig -outdir sphinxbase -o swig/sphinxbase/ad_wrap.c swig/sphinxbase/ad.i
    creating build
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/swig
    creating build/temp.macosx-10.7-x86_64-3.6/swig/sphinxbase
    creating build/temp.macosx-10.7-x86_64-3.6/deps
    creating build/temp.macosx-10.7-x86_64-3.6/deps/sphinxbase
    creating build/temp.macosx-10.7-x86_64-3.6/deps/sphinxbase/src
    creating build/temp.macosx-10.7-x86_64-3.6/deps/sphinxbase/src/libsphinxad
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -I/System/Library/Frameworks/OpenAL.framework/Versions/A/Headers -Ideps/sphinxbase/include/android -I/anaconda3/include/python3.6m -c swig/sphinxbase/ad_wrap.c -o build/temp.macosx-10.7-x86_64-3.6/swig/sphinxbase/ad_wrap.o -Wno-macro-redefined -Wno-sign-compare -Wno-logical-op-parentheses
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -I/System/Library/Frameworks/OpenAL.framework/Versions/A/Headers -Ideps/sphinxbase/include/android -I/anaconda3/include/python3.6m -c deps/sphinxbase/src/libsphinxad/ad_openal.c -o build/temp.macosx-10.7-x86_64-3.6/deps/sphinxbase/src/libsphinxad/ad_openal.o -Wno-macro-redefined -Wno-sign-compare -Wno-logical-op-parentheses
    deps/sphinxbase/src/libsphinxad/ad_openal.c:43:10: fatal error: 'al.h' file not found
    #include <al.h>
             ^~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/rz/shzsvwdn5wb1dtt_kz8j5j3w0000gp/T/pip-build-ynl5coeg/pocketsphinx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/rz/shzsvwdn5wb1dtt_kz8j5j3w0000gp/T/pip-jefu9wtk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/rz/shzsvwdn5wb1dtt_kz8j5j3w0000gp/T/pip-build-ynl5coeg/pocketsphinx/

**Comment by manuelcaeiro** [comment]
Hi KoStard,
Are a developer of textract?
There are a lot of non answered questions for a very long time.
Do you know if this project is still active?

**Comment by KoStard** [comment]
Hi Dean.
Sorry, but not, I’m not a textract developer, I have just added an issue to the GitHub repository of textract :)

With regards KoStard

**Comment by StevenMapes** [comment]
I fixed this issue today on my fork (https://github.com/StevenMapes/textract/tree/osx-pocketsphinx-fix) and has sent a PR

The fix is simple, just update requirements.txt to support newer versions of pocketsphnix. Whilst 0.1.3 works on debian based OS it fails on OSX but 0.1.15 works

**Comment by Jimtomr** [comment]
I met the same issue on MacOS Mojave and tried @StevenMapes 's solution, it works well.

**Comment by hobson** [comment]
`pip install git+https://github.com/StevenMapes/textract` is the key to happiness

**Comment by ChorlosBronson** [comment]
@StevenMapes for president ^_^

**Comment by nelsonlin2708968** [comment]
Praise be to @StevenMapes

**Comment by dianaascher** [comment]
Was hoping pip install git+https://github.com/StevenMapes/textract would also work with Mac OS Mojave 10.14.4, but I get the following error:

 1 warning generated.
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ascher/anaconda3/include -arch x86_64 -I/Users/ascher/anaconda3/include -arch x86_64 -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -I/System/Library/Frameworks/OpenAL.framework/Versions/A/Headers -I/Users/ascher/anaconda3/include/python3.7m -c deps/sphinxbase/src/libsphinxad/ad_openal.c -o build/temp.macosx-10.7-x86_64-3.7/deps/sphinxbase/src/libsphinxad/ad_openal.o -Wno-macro-redefined -Wno-sign-compare -Wno-logical-op-parentheses
    deps/sphinxbase/src/libsphinxad/ad_openal.c:43:10: fatal error: 'al.h' file not found
    #include <al.h>
             ^~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/ascher/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/05/d7bs3ct53xz1pbl3fhvdhwgw0000gn/T/pip-install-0uuk_q7n/pocketsphinx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/05/d7bs3ct53xz1pbl3fhvdhwgw0000gn/T/pip-record-l8hav14q/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/05/d7bs3ct53xz1pbl3fhvdhwgw0000gn/T/pip-install-0uuk_q7n/pocketsphinx/


Anyone else have this issue?

**Comment by StevenMapes** [comment]
@dianaascher - I take it that you've installed all of the dependencies for OSX? - https://textract.readthedocs.io/en/stable/installation.html#osx

Do you already have pocketsphinx installed? If you do, is it an older version than 0.1.15?

**Comment by pickfire** [comment]
I faced the same issue when `pip install git+https://github.com/StevenMapes/textract` in macOS Mojave 10.14.4 as well.

```
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -I/System/Library/Frameworks/OpenAL.framework/Versions/A/Headers -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/Users/jye/recommender.semut.work/venv/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c swig/sphinxbase/ad_openal_wrap.c -o build/temp.macosx-10.14-x86_64-3.7/swig/sphinxbase/ad_openal_wrap.o -Wno-macro-redefined -Wno-sign-compare -Wno-logical-op-parentheses
    swig/sphinxbase/ad_openal_wrap.c:3717:12: warning: 'PyObject_AsWriteBuffer' is deprecated [-Wdeprecated-declarations]
        res2 = PyObject_AsWriteBuffer(obj1, &buf2, &size2);
               ^
    /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m/abstract.h:503:40: note: 'PyObject_AsWriteBuffer' has been explicitly marked deprecated here
                                           Py_DEPRECATED(3.0);
                                           ^
    /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pyport.h:493:54: note: expanded from macro 'Py_DEPRECATED'
    #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                         ^
    1 warning generated.
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -I/System/Library/Frameworks/OpenAL.framework/Versions/A/Headers -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/Users/jye/recommender.semut.work/venv/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c deps/sphinxbase/src/libsphinxad/ad_openal.c -o build/temp.macosx-10.14-x86_64-3.7/deps/sphinxbase/src/libsphinxad/ad_openal.o -Wno-macro-redefined -Wno-sign-compare -Wno-logical-op-parentheses
    deps/sphinxbase/src/libsphinxad/ad_openal.c:43:10: fatal error: 'al.h' file not found
    #include <al.h>
             ^~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/jye/recommender.semut.work/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/07/071vy_z12494xlsr4csjb5yc0000gn/T/pip-install-6hdngba4/pocketsphinx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/07/071vy_z12494xlsr4csjb5yc0000gn/T/pip-record-j99tj64w/install-record.txt --single-version-externally-managed --compile --install-headers /Users/jye/recommender.semut.work/venv/include/site/python3.7/pocketsphinx" failed with error code 1 in /private/var/folders/07/071vy_z12494xlsr4csjb5yc0000gn/T/pip-install-6hdngba4/pocketsphinx/
```

**Comment by StevenMapes** [comment]
@pickfire and @dianaascher 
I've tested my fork on Mojave 10.14.4 with Python 3.6.4 and it installs perfectly (assuming you have installed the requirements.

I've not tested with Python 3.7 though. Are you both using that as it may be incompatible with something

**Comment by dianaascher** [comment]
Yes, I’m using 3.7.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by StevenMapes** [comment]
@pickfire, @dianaascher - It seems that there is an issue with PocketSphinx on Mojave, please see https://github.com/bambocher/pocketsphinx-python/issues/28 it looks like you may need to fork it, change a file and then fork this project (or my fork) and update it's requirements to use your new forked version

**Comment by dianaascher** [comment]
@StevenMapes @pickfire 

Thanks for the instructions. I’ll see if I can get it to work and report back.

**Comment by abhinavjonnada82** [comment]
@StevenMapes @pickfire 
Hey,
I've followed above aforementioned steps. But I still get the same error `fatal error: 'al.h' file not found`.
Even after including 
`#include <OpenAL/al.h>`
`#include <OpenAL/alc.h>`

Can you help me out!!

**Comment by nnisse** [comment]
@abhinavjonnada82 

I used [this person's fix](https://github.com/bambocher/pocketsphinx-python/issues/28#issuecomment-334493324) and it worked like a charm, after that I cloned StevenMapes' miracle fix and that did it.

**Comment by jpweytjens** [comment]
Textract has been updated to `1.6.2.` which makes pocketsphinx optional. It's not currently available on PyPi, but in the meanwhile you can install it with

`pip install git+https://github.com/deanmalmgren/textract.git`
